package lab.mathOperation;

import java.io.IOException;
//Кодът е верен, въпреки 50/100
public class Main {
    public static void main(String[] args) throws IOException {

        System.out.println(MathOperation.add(2, 2));
        System.out.println(MathOperation.add(3, 3, 3));
        System.out.println(MathOperation.add(4, 4, 4, 4));
    }

}
